### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by aaronxn** [jbmorley/evernote-bookmarks#2]
The script worked on about half of my Evernote Exports, the other half had this error:

Traceback (most recent call last):
  File "./evernote-bookmarks", line 88, in <module>
    main()
  File "./evernote-bookmarks", line 85, in main
    convert(options.input, options.output)
  File "./evernote-bookmarks", line 52, in convert
    source_url = note.find('note-attributes').find('source-url')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by jbmorley** [comment]
Can you provide an example of the failing input file?

**Comment by aaronxn** [comment]
I've uploaded an 85.4 MB file I am trying to import to pinboard. This file produces the error. It's a set of 243 Evernote notes of crawled web links. 

File: [A1d.enex](http://www.filedropper.com/a1d)

**Comment by jbmorley** [comment]
Cool. I can take a look at why it's failing on Monday. Currently away on vacation :).

**Comment by aaronxn** [comment]
Excellent!

**Comment by jbmorley** [comment]
Unfortunately it looks like a number of the notes in the export file do not have a source URL set. For example:

``` xml
<note><title>Defining &quot;Diaspora Jewry&quot;</title><content><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>

    <div>

        <p><span>Defining &quot;Diaspora Jewry&quot;</span></p>

        <p><span><a href="http://hamodia.com/2016/04/17/defining-diaspora-jewry/">http://hamodia.com/2016/04/17/defining-diaspora-jewry/</a></span></p>

        <p><span>Reform clergyman Rick Jacobs, who serves as president of the Union for Reform Judaism, recently made a comment of interest to a secular Jewish newspaper. It was in response to chareidi opposition in Israel to a plan that would set aside an area adjacent to the Kosel Maaravi to accommodate unorthodox services. But his words were also aimed at the larger issue of religious standards in Israel for things like geirus, gittin v'kiddushin and the official recognition and government funding of Jewish movements that do not accept halachah as the arbiter of Jewish religious questions. What the Reform leader said was that, if Israel shuns compromise with the American Reform movement, &quot;it will signal a serious rupture in the relationship between Diaspora Jewry and the Jewish state.&quot; And he went on to contend that &quot;Reform Jewish leaders speak up every day on behalf of the State of Israel on the college campus and in our communities. We are asked to speak up for Israel, even as Israel treats Reform Judaism as inauthentic.&quot; If, by that latter statement, Jacobs means to imply that Reform Jews' support for Israel is contingent on the state's adoption of the Reform movement's religious matters determinations as an official counterpart to Israel's halachah-respecting standard, it is astonishingly revealing. Threatening to hold his constituents' support for Israel hostage until his movement is considered equal with the Judaism of the ages says much about the depth of Reform commitment to Israel's security...</span></p>

    </div>

</en-note>
]]></content><created>20160418T044812Z</created></note>
```

**Comment by jbmorley** [comment]
As of 3e7dcda20d9c3c0c51ca38bb6c9dee43ea78ecec `evernote-bookmarks` will no longer fail when encountering these notes and will, instead, warn and detail the number of notes that could not be imported at the end.

**Comment by jbmorley** [comment]
I've done my best to do something sensible in the case where no `source-url` field can be found (see 52dd7321656a99aaa216e8b3d806d9362393a8e5). This parses the contents of the note and uses the first `a` tag it finds. If no `a` containing an `href` property can be found, it uses the text of the first `a` tag it finds. Otherwise, the note is ignored.
